################ French language ##################
[fr]
languageName = "Français"
languageCode = "fr-FR"
contentDir = "content/french"
weight = 1

################# English language ################
[en]
languageName = "English"
languageCode = "en-US"
contentDir = "content/english"
weight = 2
